### ISSUE TITLE
Problem running quickstart tutorial

### ISSUE THREAD

**Issue by grahaminn** [MichelangeloConserva/Colosseum#2]
1/ I tried following the instructions to install here:https://michelangeloconserva.github.io/Colosseum/mds/installation.html and found that the install process fails due to use of 
the 'imp' package, which is not available in versions of python from 3.10 onwards. I submitted a PR which should fix this, but in the meantime I installed an older python version in my colosseum conda environment (currently on python 3.9.13)

2/ That got install to work. I took the code from the quickstart tutorial (including the necessary imports) and put it all in a simple file test.py (please let me know if this is the wrong approach)

3/ I run the code with python test.py, and get the following error: -

(colosseum) grahaminnocent@Grahams-MacBook-Pro Colosseum % python test.py                                                   
Traceback (most recent call last):
  File "/Users/grahaminnocent/Colosseum/test.py", line 286, in <module>
    hyperopt_agents_and_benchmarks = sample_agent_configs_and_benchmarks_for_hyperopt([QLearningAgent], SMALL_HYPEROPT_CONF)
  File "/Users/grahaminnocent/anaconda3/envs/colosseum/lib/python3.9/site-packages/colosseum/hyperopt/utils.py", line 53, in sample_agent_configs_and_benchmarks_for_hyperopt
    for cl in get_colosseum_mdp_classes(True):
  File "/Users/grahaminnocent/anaconda3/envs/colosseum/lib/python3.9/site-packages/colosseum/utils/miscellanea.py", line 139, in get_colosseum_mdp_classes
    return _get_colosseum_mdp_classes()
  File "/Users/grahaminnocent/anaconda3/envs/colosseum/lib/python3.9/site-packages/colosseum/utils/miscellanea.py", line 148, in _get_colosseum_mdp_classes
    return [
  File "/Users/grahaminnocent/anaconda3/envs/colosseum/lib/python3.9/site-packages/colosseum/utils/miscellanea.py", line 152, in <listcomp>
    importlib.import_module(
  File "/Users/grahaminnocent/anaconda3/envs/colosseum/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'colosseum.lib'

Any suggestions welcome!

**Comment by MichelangeloConserva** [comment]
Did the pull request fixed this issue?
